-- Discount codes for partner brands.
--
-- Until now a brand row carried only free-text `discount_info` ("%15 indirim")
-- and members proved membership with their personal QR code
-- (`user_qr_codes`, untouched here — that stays the identity credential and is
-- also what a cashier scans to attach a shared-code redemption to a member).
--
-- A brand can now hand us one or more actual codes, each with its own
-- validity window, redemption cap and single-use-per-member flag. Codes the
-- brand doesn't supply are generated by us from the discount percentage
-- (EYB10 for %10 — see src/lib/discountCode.ts).

-- Note on gen_random_uuid(): the older migrations in this repo call
-- uuid_generate_v4(), which needs the uuid-ossp extension to be both installed
-- and on the search_path. No migration here ever enables it, so it can be
-- missing — and because the Supabase SQL editor runs a whole script in one
-- transaction, one unresolvable function rolls back every table above it too.
-- gen_random_uuid() is built into Postgres 13+, so it always resolves.

-- Helpers, both SECURITY DEFINER so a policy using them never re-enters RLS
-- on the table it is protecting (see the 42P17 recursion incident fixed in
-- 20260831120000_fix_roles_rls_recursion.sql).
CREATE OR REPLACE FUNCTION public.is_staff(check_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM roles
    WHERE user_id = check_user_id AND role IN ('admin', 'moderator')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_dernek_uyesi(check_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = check_user_id AND membership_tier = 'dernek_uyesi'
  );
$$;

-- A code (campaign) offered by a brand.
CREATE TABLE IF NOT EXISTS brand_discount_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id UUID NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  -- Shown to members instead of the brand's generic discount_info when set.
  label TEXT,
  discount_info TEXT,
  -- 'brand': the company gave us this code. 'generated': we produced it.
  source TEXT NOT NULL DEFAULT 'brand' CHECK (source IN ('brand', 'generated')),
  -- When true each member gets their own derived code (EYB10-7F3K2A) that can
  -- be redeemed once; when false everyone shares `code`.
  is_single_use BOOLEAN NOT NULL DEFAULT false,
  valid_from TIMESTAMP WITH TIME ZONE,
  valid_until TIMESTAMP WITH TIME ZONE,
  -- Total redemptions allowed across all members; NULL = unlimited.
  max_redemptions INTEGER CHECK (max_redemptions IS NULL OR max_redemptions > 0),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Codes are unique platform-wide (case-insensitively) so a cashier-typed code
-- always resolves to exactly one brand, and so the generator can settle
-- collisions between two brands that both give %10.
CREATE UNIQUE INDEX IF NOT EXISTS idx_brand_discount_codes_code_unique
  ON brand_discount_codes (lower(code));
CREATE INDEX IF NOT EXISTS idx_brand_discount_codes_brand
  ON brand_discount_codes (brand_id, is_active);

-- One row per (code, member): the usage ledger the counters are computed from.
-- Rows are created by server-side API routes only (service role), never by the
-- client, so a member cannot inflate the counters or mark their own code used.
CREATE TABLE IF NOT EXISTS brand_code_usages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_code_id UUID NOT NULL REFERENCES brand_discount_codes(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  -- Only for single-use campaigns: this member's personal derived code.
  member_code TEXT,
  first_viewed_at TIMESTAMP WITH TIME ZONE,
  issued_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  redeemed_at TIMESTAMP WITH TIME ZONE,
  redeemed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  redeem_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (brand_code_id, user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_brand_code_usages_member_code_unique
  ON brand_code_usages (lower(member_code)) WHERE member_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_brand_code_usages_code
  ON brand_code_usages (brand_code_id);
CREATE INDEX IF NOT EXISTS idx_brand_code_usages_user
  ON brand_code_usages (user_id);

-- RLS: unlike `brands` (publicly readable), a code is a dues-linked perk, so
-- it is gated in the database and not only in the UI.
ALTER TABLE brand_discount_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "members_read_brand_codes" ON brand_discount_codes;
CREATE POLICY "members_read_brand_codes" ON brand_discount_codes
  FOR SELECT USING (
    public.is_dernek_uyesi(auth.uid()) OR public.is_staff(auth.uid())
  );

DROP POLICY IF EXISTS "staff_manage_brand_codes" ON brand_discount_codes;
CREATE POLICY "staff_manage_brand_codes" ON brand_discount_codes
  FOR ALL USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

ALTER TABLE brand_code_usages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_read_own_code_usages" ON brand_code_usages;
CREATE POLICY "users_read_own_code_usages" ON brand_code_usages
  FOR SELECT USING (auth.uid() = user_id OR public.is_staff(auth.uid()));

-- No member INSERT/UPDATE policy on purpose: issuing and redeeming go through
-- /api/brand-codes/* and /api/admin/brand-codes/redeem.
DROP POLICY IF EXISTS "staff_manage_code_usages" ON brand_code_usages;
CREATE POLICY "staff_manage_code_usages" ON brand_code_usages
  FOR ALL USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));
